export const SELECT_CHAT = 'SELECT_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const UPDATE_MESSAGES_REQUEST = 'UPDATE_MESSAGES_REQUEST';
export const UPDATE_MESSAGES_SUCCESS = 'UPDATE_MESSAGES_SUCCESS';
export const UPDATE_MESSAGES_FAIL = 'UPDATE_MESSAGES_FAIL';

export const RECENT_CHAT_REQUEST = 'RECENT_CHAT_REQUEST';
export const RECENT_CHAT_FAIL = 'RECENT_CHAT_FAIL';
export const RECENT_CHAT_SUCCESS = 'RECENT_CHAT_SUCCESS';
//To add in userActions.js
export const RECENT_CHAT_RESET = 'RECENT_CHAT_RESET';

export const UPDATE_RECENT_CHAT_REQUEST = 'UPDATE_RECENT_CHAT_REQUEST';
export const UPDATE_RECENT_CHAT_FAIL = 'UPDATE_RECENT_CHAT_FAIL';
export const UPDATE_RECENT_CHAT_SUCCESS = 'UPDATE_RECENT_CHAT_SUCCESS';

export const NEW_CREATED_CHAT = 'NEW_CREATED_CHAT';
