export const MOSTSEARCH_CREATE_REQUEST = "MOSTSEARCH_CREATE_REQUEST";
export const MOSTSEARCH_CREATE_SUCCESS = "MOSTSEARCH_CREATE_SUCCESS";
export const MOSTSEARCH_CREATE_FAIL = "MOSTSEARCH_CREATE_FAIL";

export const MOSTSEARCH_LIST_REQUEST = "MOSTSEARCH_LIST_REQUEST";
export const MOSTSEARCH_LIST_SUCCESS = "MOSTSEARCH_LIST_SUCCESS";
export const MOSTSEARCH_CREATE_SAVE = "MOSTSEARCH_CREATE_SAVE";
export const MOSTSEARCH_LIST_FAIL = "MOSTSEARCH_LIST_FAIL";
;