const CommunityGuidelines = {
  name: "Community Guidelines",
  title: "Community Guidelines",
  text: "Be respectful. Respect is the cornerstone of a strong community. Every member should feel welcome, no matter who they are or where they come from. Please be friendly and welcoming if you are an experienced member. If you are new, take some time to look around and be open to learning from experienced sellers and buyers. Keep it clean. As a peer-to-peer community, we expect users to keep the asOne Community a safe destination for all users. Your contributions should be respectful and appropriate for all ages. Be accurate. A thriving community has trustworthy content from honorable contributors. Your content should be true and accurate, to the best of your knowledge. Stay open minded - but have your say. Opinions and different points of view are welcomed and can be discussed (and even disagreed about) in a frank, but calm and reasonable manner. Feedback can be true while also giving a different point of view; please be open to hearing differing opinions as there are multiple ways to successfully sell and buy on asOne. Share meaningful contributions. Please use search to see if your question has already been answered. Get the help you need. Please ask for recommendations for tools to help run your business, to find items to purchase, or to share your items or listings to get feedback or provide examples to other users. It’s appropriate for users to also respond to these types of questions with listings, products, or services. Share, celebrate… and have fun! Buying and selling on asOne isn’t the only thing that is important to you. Share your hobby, or complain about your pet peeve. Celebrate your latest thrifting score, or post a death pile photo. This community welcomes hearing about your latest personal triumph, a moment where you need support, or just an amazing meal you made (in the appropriate forum). This community is designed to connect people, and the more we get to know each other, the more we people will grow together, asOne! ",
};
const PrivacyPolicy = {
  name: "Privacy Policy",
  title: "Privacy Policy",
  text: "PROSHOP respect the privacy of our users. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website PROSHOP. Please read this privacy policy carefully. If you disagree with the terms of this privacy policy, please do not access the site. We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the Last Updated date of this Privacy Policy. Any changes or modifications will be effective immediately upon posting the updated Privacy Policy on the Site. You waive the right to receive specific notice of each such change or modification. You are encouraged to periodically review this Privacy Policy to stay informed of updates. You will be deemed to have been made aware of, will be subject to, and will be deemed to have accepted the changes in any revised Privacy Policy by your continued use of the Site after the date such revised Privacy Policy is posted. ",
};
const TermsOfUse = {
  name: " Terms Of Use",
  title: "Terms Of Use",
  text: "In connection with using or accessing our Services you agree to comply with this User Agreement, our policies, our terms, and all applicable laws, rules, and regulations, and you will not: breach or circumvent any laws, regulations, third-party rights or our systems, Services, policies, or determinations of your account status; use our Services if you are not able to form legally binding contracts (for example, if you are under 18 years old), or are temporarily or indefinitely suspended from using our Services, or are a person with whom transactions are prohibited under economic or trade sanctions; fail to pay for items purchased by you, unless you have a valid reason as set out in an asOne policy, for example, where the seller has materially changed the item's description after you bid (see our Unpaid item policy); fail to give items sold by you, unless you have a valid reason as set out in an asOne policy; manipulate the price of any item or interfere with any other user's listings; take any action that may undermine the feedback or ratings systems (our Feedback policies); transfer your asOne account (including feedback) and user ID to another party without our consent; share your log in credentials with any third parties. If you require that authorized third parties (employees, agents, etc.) have access to your account we offer a Multi-User Account Access program for that purpose. create listings, post, or upload content in inappropriate categories or areas on our sites; post false, inaccurate, misleading, deceptive, defamatory, or libelous content; distribute or post spam, unsolicited or bulk electronic communications, chain letters, or pyramid schemes; distribute viruses or any other technologies that may harm asOne or the interests or property of users; use any robot, spider, scraper, data mining tools, data gathering and extraction tools, or other automated means to access our Services for any purpose, except with the prior express permission of asOne; circumvent any technical measures used to provide our Services. interfere with the functioning of our Services, such as by imposing an unreasonable or disproportionately large load on our infrastructure; export or re-export any asOne application or tool, except in compliance with the export control laws, and rules and policies of any relevant jurisdictions."
};

export { CommunityGuidelines, PrivacyPolicy, TermsOfUse };
